Pilot 1828: Add file type as part of Redis key
PilotDataPlatform/dataops pull request #53
Opened 2022-11-08 16:55 UTC by QXgu

## Summary

Pilot 1828: Add file type as part of Redis key

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1898

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-11-08 21:07 UTC, afmam commented on config.py
> +    PORT: int = 8001
Is there reason why port was changed?

2022-11-08 21:22 UTC, afmam commented on models/file_ops_models.py
> +                'target_type': "batch",
Does "batch" indicate to front-end combination of file/folders in a copy request? If so, how do they differentiate between them?

2022-11-08 21:22 UTC, afmam requested changes
Left 2 comments

2022-11-08 21:23 UTC, QXgu commented on config.py
> +    PORT: int = 8001
For local test though, I will change it back!

2022-11-08 21:24 UTC, QXgu commented on models/file_ops_models.py
> +                'target_type': "batch",
The batch will be the situation that multiple files and folders are selected at once and trigger one pipeline. The frontend will have a different logo for that

2022-11-08 21:36 UTC, QXgu commented
@afmam Changes back now. Please check

2022-11-08 21:40 UTC, afmam approved these changes

2022-12-15 15:21 UTC, erikdvlp commented
Deprecated.

2022-12-15 15:21 UTC, closed without merging